
GET http://localhost:4000/users

###
GET http://localhost:4000/users/5f0eb6a5eb91461fc05e8469

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "firstname" : "Abhijith",
    "surname" : "Remesh",
    "email" : "abhijithremesh@gail.com",
    "password": "Abhi" 
}

###
DELETE http://localhost:4000/users/5f0ec324a0524233f866c213

###

PATCH http://localhost:4000/users/5f0ec4c71a40171e903e53b7
Content-Type: application/json

{
    "firstname" : "Shambhu",
    "lastname" : "Remesh",
    "email" : "shambhuremesh@gmail.com"
}